# Generated by Django 3.1.5 on 2021-01-22 13:34

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('detail_title', models.CharField(max_length=100)),
                ('conference_date', models.DateField(auto_now_add=True)),
                ('address', models.CharField(max_length=255)),
                ('venue', models.CharField(max_length=200)),
                ('is_featured', models.BooleanField(default=False)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('description', ckeditor.fields.RichTextField(default='')),
                ('registration', ckeditor.fields.RichTextField(default='')),
                ('image', models.ImageField(upload_to='bannerImages/')),
            ],
        ),
    ]
