# Generated by Django 3.1.5 on 2021-01-21 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_title', models.CharField(max_length=100)),
                ('banner_dateOfEvent', models.DateField(max_length=100)),
                ('banner_address', models.TextField()),
                ('banner_image', models.ImageField(upload_to='bannerImages/')),
                ('tab1_title', models.CharField(max_length=100)),
                ('tab1_description', models.TextField()),
                ('tab2_title', models.CharField(max_length=100)),
                ('tab2_description', models.TextField()),
                ('tab3_title', models.CharField(max_length=100)),
                ('tab3_description', models.TextField()),
                ('tab3_venue', models.CharField(max_length=100)),
                ('tab3_address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='Hotel/')),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bannerPortfolio.banner')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('register_price', models.IntegerField()),
                ('register_late_price', models.IntegerField()),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bannerPortfolio.banner')),
            ],
        ),
    ]
