# Generated by Django 3.1.5 on 2021-01-22 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bannerPortfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='conference_date',
        ),
    ]
