# Generated by Django 3.1.5 on 2021-01-22 13:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bannerPortfolio', '0002_remove_conference_conference_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='conference_date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
