# Generated by Django 3.1.5 on 2021-01-21 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bannerPortfolio', '0002_book_bookdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookdetails',
            name='bok',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='category_title',
        ),
        migrations.AlterField(
            model_name='category',
            name='banner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Categorybanner', to='bannerPortfolio.banner'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='banner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Hotelbanner', to='bannerPortfolio.banner'),
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BookDetails',
        ),
    ]
