# Generated by Django 3.1.5 on 2021-01-22 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bannerPortfolio', '0003_conference_conference_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='Hotel/')),
                ('redirect_url', models.URLField()),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Conference', to='bannerPortfolio.conference')),
            ],
        ),
    ]
