# Generated by Django 3.1.5 on 2021-01-22 16:32

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bannerPortfolio', '0004_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='travel_info',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='conference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conferenceHotel', to='bannerPortfolio.conference'),
        ),
    ]
